// <auto-generated>
// Generated by scripts~/set-version.mjs. Do not edit manually.
// </auto-generated>
namespace Appstack
{
    internal static class AppstackVersion
    {
        internal const string PackageVersion = "1.0.0";
        internal const string WrapperVersion = "unity-" + PackageVersion;
    }
}
