#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const rootPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = path.join(rootPath, 'package.json');
const versionSourcePath = path.join(rootPath, 'Runtime', 'AppstackVersion.cs');
const semverPattern =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/;

function fail(message) {
  console.error(`Version error: ${message}`);
  process.exit(1);
}

function validateVersion(version, label) {
  if (!semverPattern.test(version)) {
    fail(`${label} must be a semantic version, received "${version}".`);
  }
}

function versionSource(version) {
  return `// <auto-generated>
// Generated by scripts~/set-version.mjs. Do not edit manually.
// </auto-generated>
namespace Appstack
{
    internal static class AppstackVersion
    {
        internal const string PackageVersion = "${version}";
        internal const string WrapperVersion = "unity-" + PackageVersion;
    }
}
`;
}

function readManifest() {
  try {
    return JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  } catch (error) {
    fail(`unable to read package.json: ${error.message}`);
  }
}

const args = process.argv.slice(2);
if (args[0] === '--check') {
  if (args.length > 2) {
    fail('usage: node scripts~/set-version.mjs --check [expected-version]');
  }

  const manifest = readManifest();
  validateVersion(manifest.version, 'package.json version');

  const expectedVersion = args[1];
  if (expectedVersion !== undefined) {
    validateVersion(expectedVersion, 'expected version');
    if (manifest.version !== expectedVersion) {
      fail(
        `package.json version (${manifest.version}) does not match ` +
          `expected version (${expectedVersion}).`,
      );
    }
  }

  const expectedSource = versionSource(manifest.version);
  const actualSource = fs.readFileSync(versionSourcePath, 'utf8');
  if (actualSource !== expectedSource) {
    fail(
      'Runtime/AppstackVersion.cs is stale. Run ' +
        `"node scripts~/set-version.mjs ${manifest.version}" and commit the result.`,
    );
  }

  console.log(
    `Version contract is valid: ${manifest.version} / unity-${manifest.version}`,
  );
  process.exit(0);
}

if (args.length !== 1) {
  fail('usage: node scripts~/set-version.mjs <version>');
}

const version = args[0];
validateVersion(version, 'version');

const manifest = readManifest();
manifest.version = version;
fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
fs.writeFileSync(versionSourcePath, versionSource(version));

console.log(`Updated package.json and wrapper telemetry to ${version}.`);
